/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.VitalSignHistory;
import model.VitalSigns;

/**
 *
 * @author tarushukla
 */
public class ViewPatientDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientDirectoryJPanel
     */
    int row, column;
    DefaultTableModel defaultTableModel, defaultTableModel1;
    VitalSignHistory vitalSignHistory;
    
    public ViewPatientDirectoryJPanel(VitalSignHistory vitalSignHistory) {
        initComponents();
        this.vitalSignHistory= vitalSignHistory;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePatientDirectoryData = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblPatientName = new javax.swing.JLabel();
        txtPatientAge = new javax.swing.JTextField();
        lblPatientAge = new javax.swing.JLabel();
        txtPatientContactNumber = new javax.swing.JTextField();
        lblContactNumber = new javax.swing.JLabel();
        btnUpdatePatientDetails = new javax.swing.JButton();
        jSearchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxSelectedCommunity = new javax.swing.JComboBox<>();
        lblCommunity = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPatientMinAge = new javax.swing.JTextField();
        lblPatientAge1 = new javax.swing.JLabel();
        lblMinAge = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientMaxAge = new javax.swing.JTextField();
        lblMaxAge = new javax.swing.JLabel();
        btnSearchResult = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePatientSearchResult = new javax.swing.JTable();

        jTablePatientDirectoryData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Contact", "Residence", "Community", "City", "Patient Id", "Body Temperature", "Systolic BP", "Diastolic BP", "Heart Rate", "Body Weight", "Date"
            }
        ));
        jTablePatientDirectoryData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePatientDirectoryDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePatientDirectoryData);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("Patient Directory");

        lblPatientName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblPatientName.setText("Patient Name");

        txtPatientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientAgeActionPerformed(evt);
            }
        });

        lblPatientAge.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblPatientAge.setText("Patient Age");

        lblContactNumber.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblContactNumber.setText("Contact Number");

        btnUpdatePatientDetails.setText("Update");
        btnUpdatePatientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientDetailsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Search Results");

        comboBoxSelectedCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allston", "Back Bay", "Mission Hill", "Roxbury" }));
        comboBoxSelectedCommunity.setSelectedIndex(-1);

        lblCommunity.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblCommunity.setText("Select Community");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel3.setText("Select Search Criteria");

        txtPatientMinAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientMinAgeActionPerformed(evt);
            }
        });

        lblPatientAge1.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lblPatientAge1.setText("Enter Patient Age");

        lblMinAge.setText("Min Age");

        jLabel5.setText("/");

        txtPatientMaxAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientMaxAgeActionPerformed(evt);
            }
        });

        lblMaxAge.setText("Max Age");

        btnSearchResult.setText("Search");
        btnSearchResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchResultActionPerformed(evt);
            }
        });

        jTablePatientSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "Contact", "Residence", "Community", "City", "Patient Id", "Body Temperature", "Systolic BP", "Diastolic BP", "Heart Rate", "Body Weight", "Date"
            }
        ));
        jTablePatientSearchResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePatientSearchResultMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePatientSearchResult);

        javax.swing.GroupLayout jSearchPanelLayout = new javax.swing.GroupLayout(jSearchPanel);
        jSearchPanel.setLayout(jSearchPanelLayout);
        jSearchPanelLayout.setHorizontalGroup(
            jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchPanelLayout.createSequentialGroup()
                .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSearchPanelLayout.createSequentialGroup()
                        .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jSearchPanelLayout.createSequentialGroup()
                                .addGap(496, 496, 496)
                                .addComponent(jLabel1))
                            .addGroup(jSearchPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jSearchPanelLayout.createSequentialGroup()
                                        .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(comboBoxSelectedCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(lblPatientAge1)
                                        .addGap(60, 60, 60)
                                        .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jSearchPanelLayout.createSequentialGroup()
                                                .addComponent(txtPatientMinAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5))
                                            .addComponent(lblMinAge))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaxAge)
                                            .addGroup(jSearchPanelLayout.createSequentialGroup()
                                                .addComponent(txtPatientMaxAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(72, 72, 72)
                                                .addComponent(btnSearchResult)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSearchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jSearchPanelLayout.setVerticalGroup(
            jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinAge)
                    .addComponent(lblMaxAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommunity)
                    .addComponent(comboBoxSelectedCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientAge1)
                    .addComponent(txtPatientMinAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPatientMaxAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(435, 435, 435)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblPatientName)
                                .addGap(60, 60, 60)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lblPatientAge)
                                .addGap(60, 60, 60)
                                .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lblContactNumber)
                                .addGap(60, 60, 60)
                                .addComponent(txtPatientContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(btnUpdatePatientDetails)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPatientAge)
                    .addComponent(txtPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactNumber)
                    .addComponent(txtPatientContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePatientDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientAgeActionPerformed

    private void btnUpdatePatientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientDetailsActionPerformed
        // TODO add your handling code here:

        int rowCount= jTablePatientDirectoryData.getSelectedRow();
        defaultTableModel = (DefaultTableModel)jTablePatientDirectoryData.getModel();
        String updatePatientName= "";
        int updatePatientAge;
        long updateContactNumber;
        updatePatientName =txtPatientName.getText();
        updatePatientAge = Integer.parseInt(txtPatientAge.getText());
        updateContactNumber = Long.parseLong(txtPatientContactNumber.getText());

        if(rowCount>=0){
            defaultTableModel.setValueAt(updatePatientName, rowCount, 0);
            defaultTableModel.setValueAt(updatePatientAge, rowCount, 1);
            defaultTableModel.setValueAt(updateContactNumber, rowCount, 3);
            JOptionPane.showMessageDialog(this, " Patient Details Updated");
        }
        //        populate();
        //        JOptionPane.showMessageDialog(this, " Patient Details Populate");

    }//GEN-LAST:event_btnUpdatePatientDetailsActionPerformed

    private void jTablePatientDirectoryDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePatientDirectoryDataMouseClicked
        // TODO add your handling code here:

        row= jTablePatientDirectoryData.getSelectedRow();
        column=jTablePatientDirectoryData.getSelectedColumn();
        defaultTableModel = (DefaultTableModel)jTablePatientDirectoryData.getModel();
        txtPatientName.setText(defaultTableModel.getValueAt(row, 0).toString());
        txtPatientAge.setText(defaultTableModel.getValueAt(row, 1).toString());
        txtPatientContactNumber.setText(defaultTableModel.getValueAt(row, 3).toString());

    }//GEN-LAST:event_jTablePatientDirectoryDataMouseClicked

    private void txtPatientMinAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientMinAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientMinAgeActionPerformed

    private void txtPatientMaxAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientMaxAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientMaxAgeActionPerformed

    private void btnSearchResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchResultActionPerformed
        // TODO add your handling code here:
        defaultTableModel1 = (DefaultTableModel)jTablePatientSearchResult.getModel();
        defaultTableModel1.setRowCount(0);
        String selectedCommunity = comboBoxSelectedCommunity.getSelectedItem().toString();
        int minimum;
        int maximum;
        if (txtPatientMinAge.getText()== null || txtPatientMinAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Minimum Range");
            return;
        } else{
            minimum = Integer.parseInt(txtPatientMinAge.getText());
        }
        if (txtPatientMaxAge.getText()== null || txtPatientMaxAge.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Maximum Range");
            return;
        } else{
            maximum = Integer.parseInt(txtPatientMaxAge.getText());
        }

        for (int i = 0; i < vitalSignHistory.getVitalSignArrayList().size(); i++) {
            String matchingCommunity = vitalSignHistory.getVitalSignArrayList().get(i).getCommunity();
            if (matchingCommunity.equalsIgnoreCase(selectedCommunity)) {
                int matchingAge = vitalSignHistory.getVitalSignArrayList().get(i).getPatientAge();
                if(matchingAge >= minimum  && matchingAge <= maximum){
                    double matchingSystolic = vitalSignHistory.getVitalSignArrayList().get(i).getBloodPressureSystolic();
                    double matchingDiastolic = vitalSignHistory.getVitalSignArrayList().get(i).getBloodPressureDiastolic();
                    if(matchingSystolic>120 || matchingSystolic < 90 || matchingDiastolic>80){

                        Object[] object= {vitalSignHistory.getVitalSignArrayList().get(i).getPatientName(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getPatientAge(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getPatientGender(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getContactNumber(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getResidence(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getCommunity(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getCity(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getPatientId(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getBodyTemperature(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getBloodPressureSystolic(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getBloodPressureDiastolic(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getHeartRate(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getWeight(),
                            vitalSignHistory.getVitalSignArrayList().get(i).getDate()

                        };
                        defaultTableModel1.addRow(object);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSearchResultActionPerformed

    private void jTablePatientSearchResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePatientSearchResultMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablePatientSearchResultMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchResult;
    private javax.swing.JButton btnUpdatePatientDetails;
    private javax.swing.JComboBox<String> comboBoxSelectedCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jSearchPanel;
    private javax.swing.JTable jTablePatientDirectoryData;
    private javax.swing.JTable jTablePatientSearchResult;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblMaxAge;
    private javax.swing.JLabel lblMinAge;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientAge1;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientContactNumber;
    private javax.swing.JTextField txtPatientMaxAge;
    private javax.swing.JTextField txtPatientMinAge;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables

    private void populate() {
    
    defaultTableModel = (DefaultTableModel)jTablePatientDirectoryData.getModel();
        defaultTableModel.setRowCount(0);
        
        for(VitalSigns vc : vitalSignHistory.getVitalSignArrayList()){
            Object[] row = new Object[14];
            row[0]= vc;
            row[1]= vc.getPatientAge();
            row[2]= vc.getPatientGender();
            row[3]= vc.getContactNumber();
            row[4]= vc.getResidence();
            row[5]= vc.getCommunity();
            row[6]= vc.getCity();
            row[7]= vc.getPatientId();
            row[8]= vc.getBodyTemperature();
            row[9]= vc.getBloodPressureSystolic();
            row[10]= vc.getBloodPressureDiastolic();
            row[11]= vc.getHeartRate();
            row[12]=vc.getWeight();
            row[13]= vc.getDate();
            defaultTableModel.addRow(row); 
        }  
    }
}
