/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.regex.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Profile;

/**
 *
 * @author tarushukla
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Profile profile;
    
    public CreateJPanel(Profile profile) {
        initComponents();
        this.profile = profile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeoData = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblTeleNum = new javax.swing.JLabel();
        lblFAX = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblMedic = new javax.swing.JLabel();
        lblHealthNum = new javax.swing.JLabel();
        lblBankNum = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblVehicleId = new javax.swing.JLabel();
        lblDeviceId = new javax.swing.JLabel();
        lblLinkedIn = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        lblBioId = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblUniqueID = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGeoData = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtTeleNum = new javax.swing.JTextField();
        txtFAX = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedic = new javax.swing.JTextField();
        txtHealthNum = new javax.swing.JTextField();
        txtBankNum = new javax.swing.JTextField();
        txtLicenseNum = new javax.swing.JTextField();
        txtVehicleId = new javax.swing.JTextField();
        txtDeviceId = new javax.swing.JTextField();
        txtLinkedIn = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        txtUniqueID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelValDOB = new javax.swing.JLabel();
        jLabelFAX = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSSN = new javax.swing.JLabel();
        jLabelMRN = new javax.swing.JLabel();
        jLabelHBN = new javax.swing.JLabel();
        jLabelBank = new javax.swing.JLabel();
        jLabelLicenseNumber = new javax.swing.JLabel();
        jLabelVID = new javax.swing.JLabel();
        jLabelDID = new javax.swing.JLabel();
        jLabelLinkedIn = new javax.swing.JLabel();
        jLabelIPAdd = new javax.swing.JLabel();
        jLabelUID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelGeoData = new javax.swing.JLabel();
        jButtonBio = new javax.swing.JButton();
        jLabelValTeleNum = new javax.swing.JLabel();
        jLabelBioID = new javax.swing.JLabel();
        jLabelFullFace = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile ");

        lblName.setText("Name");

        lblGeoData.setText("Geographic Data");

        lblDOB.setText("Date of Birth");

        lblTeleNum.setText("Telephone Number");

        lblFAX.setText("FAX Number");

        lblEmail.setText("Email Address");

        lblSSN.setText("Social Security Number");

        lblMedic.setText("Medical Record Number");

        lblHealthNum.setText("Health Plan Beneficiary Number");

        lblBankNum.setText("Bank Account Number");

        lblLicenseNum.setText("License Number");

        lblVehicleId.setText("Vehicle Identifier");

        lblDeviceId.setText("Device Identifier");

        lblLinkedIn.setText("LinkedIn");

        lblIPAddress.setText("Internet Protocol Address");

        lblBioId.setText("Biometric Identifier");

        lblImage.setText("Full Face Photo");

        lblUniqueID.setText("Unique Identifying Number");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtGeoData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGeoDataKeyReleased(evt);
            }
        });

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        txtDOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDOBKeyReleased(evt);
            }
        });

        txtTeleNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleNumActionPerformed(evt);
            }
        });
        txtTeleNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTeleNumKeyReleased(evt);
            }
        });

        txtFAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAXActionPerformed(evt);
            }
        });
        txtFAX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFAXKeyReleased(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSSNKeyReleased(evt);
            }
        });

        txtMedic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedicKeyReleased(evt);
            }
        });

        txtHealthNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHealthNumKeyReleased(evt);
            }
        });

        txtBankNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNumActionPerformed(evt);
            }
        });
        txtBankNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankNumKeyReleased(evt);
            }
        });

        txtLicenseNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLicenseNumKeyReleased(evt);
            }
        });

        txtVehicleId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIdActionPerformed(evt);
            }
        });
        txtVehicleId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVehicleIdKeyReleased(evt);
            }
        });

        txtDeviceId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDeviceIdKeyReleased(evt);
            }
        });

        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });
        txtLinkedIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLinkedInKeyReleased(evt);
            }
        });

        txtIPAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIPAddressKeyReleased(evt);
            }
        });

        txtUniqueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIDActionPerformed(evt);
            }
        });
        txtUniqueID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUniqueIDKeyReleased(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton1.setText("Attach");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelFAX.setForeground(new java.awt.Color(0, 51, 153));
        jLabelFAX.setText("Fax number starts with +1");

        jLabelSSN.setForeground(new java.awt.Color(0, 51, 153));
        jLabelSSN.setText("SSN : 222-222222");

        jLabelMRN.setForeground(new java.awt.Color(0, 51, 153));
        jLabelMRN.setText("6 - digit Number");

        jLabelHBN.setForeground(new java.awt.Color(0, 51, 153));
        jLabelHBN.setText("11 - digit Number");

        jLabelLicenseNumber.setForeground(new java.awt.Color(0, 51, 153));
        jLabelLicenseNumber.setText("7 - digit Number");

        jLabelVID.setForeground(new java.awt.Color(0, 51, 153));
        jLabelVID.setText("17 - digit Number");

        jLabelDID.setForeground(new java.awt.Color(0, 51, 153));
        jLabelDID.setText("32 - digit Number");

        jLabelUID.setForeground(new java.awt.Color(0, 51, 153));
        jLabelUID.setText("College ID");

        jButtonBio.setText("Attach");
        jButtonBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBioActionPerformed(evt);
            }
        });

        jLabelBioID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelFullFace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName)
                            .addComponent(lblGeoData)
                            .addComponent(lblDOB)
                            .addComponent(lblTeleNum)
                            .addComponent(lblFAX)
                            .addComponent(lblEmail)
                            .addComponent(lblSSN)
                            .addComponent(lblMedic)
                            .addComponent(lblHealthNum)
                            .addComponent(lblBankNum)
                            .addComponent(lblLicenseNum)
                            .addComponent(lblVehicleId)
                            .addComponent(lblDeviceId)
                            .addComponent(lblLinkedIn)
                            .addComponent(lblIPAddress)
                            .addComponent(lblBioId)
                            .addComponent(lblImage)
                            .addComponent(lblUniqueID))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelIPAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelLinkedIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelLicenseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelHBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMedic, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMRN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                    .addComponent(txtGeoData))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelValDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelUID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                            .addComponent(txtTeleNum, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFAX, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabelValTeleNum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelFAX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelBioID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonBio)
                                    .addComponent(jLabelFullFace, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton1)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(lblTitle)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGeoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGeoData)
                        .addComponent(txtGeoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDOB)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValTeleNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTeleNum)
                        .addComponent(txtTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFAX)
                    .addComponent(txtFAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFAX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmail)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSSN)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSSN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMedic)
                    .addComponent(txtMedic)
                    .addComponent(jLabelMRN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHealthNum)
                        .addComponent(txtHealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBankNum)
                        .addComponent(txtBankNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLicenseNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLicenseNum)
                        .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVehicleId)
                        .addComponent(txtVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDeviceId)
                        .addComponent(txtDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLinkedIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLinkedIn)
                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAddress)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblBioId))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBioID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFullFace, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniqueID)
                    .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUID))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtTeleNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleNumActionPerformed

    private void txtUniqueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIDActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void txtVehicleIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIdActionPerformed

    private void txtBankNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNumActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtFAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAXActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        profile.setName(txtName.getText());
        profile.setGeoData(txtGeoData.getText());
        profile.setDoB(txtDOB.getText());
        try{       
            profile.setTeleNumber(Long.parseLong(txtTeleNum.getText()));
          }catch(NumberFormatException ex){
             System.out.println(ex);
    }
        profile.setFaxNumber(txtFAX.getText());
        profile.setEmailAdd(txtEmail.getText());
        profile.setSsn(txtSSN.getText());
        profile.setMedicNumber(Integer.parseInt(txtMedic.getText()));
        profile.setHealthPlanNumbr(txtHealthNum.getText());
        try{
                    profile.setBankAccount(Long.parseLong(txtBankNum.getText()));

        }catch(NumberFormatException ex){
                         System.out.println(ex);

        }
        try{
        profile.setLicenseNumber(Integer.parseInt(txtLicenseNum.getText()));

        }catch(NumberFormatException ex){
                         System.out.println(ex);

        }
        profile.setVehicleIdentifier(txtVehicleId.getText());
        profile.setDeviceIdentifier(txtDeviceId.getText());
        profile.setLinkedIn(txtLinkedIn.getText());
        try{
        profile.setIpAddress(txtIPAddress.getText());

        }catch(NumberFormatException ex){
                         System.out.println(ex);

        }try{
        profile.setUniqueId(Integer.parseInt(txtUniqueID.getText()));

        }catch(NumberFormatException ex){
                         System.out.println(ex);

        }
        
        JOptionPane.showMessageDialog(this,"Profile saved!!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
             JFileChooser jfc = new JFileChooser();
             jfc.showOpenDialog(null);
			File file = jfc.getSelectedFile();
                       String filename = file.getAbsolutePath();
                        profile.setFullFace(filename);
                        Image getAbsolutePath = null;
                        ImageIcon icon = new ImageIcon(filename);
                        Image image =icon.getImage().getScaledInstance(jLabelFullFace.getWidth(), jLabelFullFace.getHeight(),Image.SCALE_SMOOTH);
			
                        jLabelFullFace.setIcon(new ImageIcon(image.getScaledInstance(jLabelFullFace.getWidth(), jLabelFullFace.getHeight(),Image.SCALE_SMOOTH)));


        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
         String input2 = txtName.getText();
        if(!input2.matches("^[a-zA-Z ]{1,90}$")){
            jLabelName.setText("Name is Invalid");
        }else{
            jLabelName.setText(null);

        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtGeoDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeoDataKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[a-zA-Z0-9-/, .]{1,80}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtGeoData.getText());
        if(!match.matches()){
         jLabelGeoData.setText("Invalid Address");
        }else{
         jLabelGeoData.setText(null);

        }
    }//GEN-LAST:event_txtGeoDataKeyReleased

    private void txtDOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDOBKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[0-9]{1,2}[/][0-9]{1,2}[/][0-9]{4,4}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtDOB.getText());
        if(!match.matches()){
            jLabelValDOB.setText("Date Of Birth is Invalid");
        }else{
                        jLabelValDOB.setText(null);

        }
    }//GEN-LAST:event_txtDOBKeyReleased

    private void txtTeleNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleNumKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[0-9]{10}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtTeleNum.getText());
         
        if(!match.matches()){
                        jLabelValTeleNum.setText("Invalid Telephone Number");
        }else{
           jLabelValTeleNum.setText(null);

        }
    }//GEN-LAST:event_txtTeleNumKeyReleased

    private void txtFAXKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFAXKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[+1][0-9]{11}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtFAX.getText());
         
        if(!match.matches()){
            jLabelFAX.setText("Invalid FAX Number");
        }else{
           jLabelFAX.setText(null);

        }
    }//GEN-LAST:event_txtFAXKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
         String input2 = txtEmail.getText();
        if(!input2.matches("^[a-zA-Z0-9_-]{1,30}[@][a-z]{1,9}[.][a-z]{1,3}$")){
            jLabelEmail.setText("Email address is Invalid");
        }else{
            jLabelEmail.setText(null);

        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtSSNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[0-9]{3}[-][0-9]{6}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtSSN.getText());
         
        if(!match.matches()){
            jLabelSSN.setText("Invalid SSN Number");
        }else{
           jLabelSSN.setText(null);

        }   
    }//GEN-LAST:event_txtSSNKeyReleased

    private void txtMedicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicKeyReleased
        // TODO add your handling code here:
         String patterninput = "^[0-9]{6}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtMedic.getText());
         
        if(!match.matches()){
            jLabelMRN.setText("Invalid Medical Record Number");
        }else{
           jLabelMRN.setText(null);

        }  
    }//GEN-LAST:event_txtMedicKeyReleased

    private void txtHealthNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealthNumKeyReleased
        // TODO add your handling code here:
         String patterninput = "^[A-Z0-9]{11}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtHealthNum.getText());
         
        if(!match.matches()){
            jLabelHBN.setText("Invalid Health Insurance Number");
        }else{
           jLabelHBN.setText(null);

        }
    }//GEN-LAST:event_txtHealthNumKeyReleased

    private void txtBankNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankNumKeyReleased
        // TODO add your handling code here:
         String patterninput = "^[0-9]{10}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtBankNum.getText());
         
        if(!match.matches()){
            jLabelBank.setText("Invalid Bank Account Number");
        }else{
           jLabelBank.setText(null);

        }
    }//GEN-LAST:event_txtBankNumKeyReleased

    private void txtLicenseNumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicenseNumKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[0-9]{7}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtLicenseNum.getText());
           jLabelLicenseNumber.setText("Start no. with SA");

        if(!match.matches()){
            jLabelLicenseNumber.setText("Invalid License Number");
        }else{
           jLabelLicenseNumber.setText(null);

        }
    }//GEN-LAST:event_txtLicenseNumKeyReleased

    private void txtVehicleIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehicleIdKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[A-Z0-9]{17}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtVehicleId.getText());
        if(!match.matches()){
            jLabelVID.setText("Invalid Vehicle Number");
        }else{
           jLabelVID.setText(null);

        }
    }//GEN-LAST:event_txtVehicleIdKeyReleased

    private void txtDeviceIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeviceIdKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[A-Z0-9]{32}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtDeviceId.getText());
        if(!match.matches()){
            jLabelDID.setText("Invalid Device Number");
        }else{
           jLabelDID.setText(null);

        }
    }//GEN-LAST:event_txtDeviceIdKeyReleased

    private void txtLinkedInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkedInKeyReleased
        // TODO add your handling code here:
         String patterninput = "^[a-z]{1,20}[-][a-z]{1,20}[-][0-9]{1,10}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtLinkedIn.getText());
        if(!match.matches()){
            jLabelLinkedIn.setText("Invalid LinkedIn");
        }else{
           jLabelLinkedIn.setText(null);

        }
    }//GEN-LAST:event_txtLinkedInKeyReleased

    private void txtIPAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAddressKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[0-9]{0,4}[.][0-9]{0,4}[.][0-9]{0,4}[.][0-9]{0,4}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtIPAddress.getText());
        if(!match.matches()){
            jLabelIPAdd.setText("Invalid IP Address");
        }else{
           jLabelIPAdd.setText(null);

        }
    }//GEN-LAST:event_txtIPAddressKeyReleased

    private void txtUniqueIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUniqueIDKeyReleased
        // TODO add your handling code here:
        String patterninput = "^[0-9]{9}$";
        Pattern pattern1 = Pattern.compile(patterninput);
        Matcher match = pattern1.matcher(txtUniqueID.getText());
        if(!match.matches()){
            jLabelUID.setText("Invalid Unique Id - College Id");
        }else{
           jLabelUID.setText(null);

        }
    }//GEN-LAST:event_txtUniqueIDKeyReleased

    private void jButtonBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBioActionPerformed
        // TODO add your handling code here:
         JFileChooser jfc = new JFileChooser();
             jfc.showOpenDialog(null);
			File file = jfc.getSelectedFile();
                       String filename = file.getAbsolutePath();
                        profile.setBioId(filename);
                        Image getAbsolutePath = null;
                        ImageIcon icon = new ImageIcon(filename);
                        Image image =icon.getImage().getScaledInstance(jLabelBioID.getWidth(), jLabelBioID.getHeight(),Image.SCALE_SMOOTH);
                        jLabelBioID.setIcon(new ImageIcon(image.getScaledInstance(jLabelBioID.getWidth(), jLabelBioID.getHeight(),Image.SCALE_SMOOTH)));

    }//GEN-LAST:event_jButtonBioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBio;
    private javax.swing.JLabel jLabelBank;
    private javax.swing.JLabel jLabelBioID;
    private javax.swing.JLabel jLabelDID;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFAX;
    private javax.swing.JLabel jLabelFullFace;
    private javax.swing.JLabel jLabelGeoData;
    private javax.swing.JLabel jLabelHBN;
    private javax.swing.JLabel jLabelIPAdd;
    private javax.swing.JLabel jLabelLicenseNumber;
    private javax.swing.JLabel jLabelLinkedIn;
    private javax.swing.JLabel jLabelMRN;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSSN;
    private javax.swing.JLabel jLabelUID;
    private javax.swing.JLabel jLabelVID;
    private javax.swing.JLabel jLabelValDOB;
    private javax.swing.JLabel jLabelValTeleNum;
    private javax.swing.JLabel lblBankNum;
    private javax.swing.JLabel lblBioId;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceId;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFAX;
    private javax.swing.JLabel lblGeoData;
    private javax.swing.JLabel lblHealthNum;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblLinkedIn;
    private javax.swing.JLabel lblMedic;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTeleNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUniqueID;
    private javax.swing.JLabel lblVehicleId;
    private javax.swing.JTextField txtBankNum;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDeviceId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFAX;
    private javax.swing.JTextField txtGeoData;
    private javax.swing.JTextField txtHealthNum;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtLinkedIn;
    private javax.swing.JTextField txtMedic;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTeleNum;
    private javax.swing.JTextField txtUniqueID;
    private javax.swing.JTextField txtVehicleId;
    // End of variables declaration//GEN-END:variables

}
