/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import model.UberCatalog;
import model.UberDetails;

/**
 *
 * @author tarushukla
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    UberCatalog catalog;
            
    public CreateJPanel(UberCatalog catalog) {
        initComponents();
        this.catalog= catalog;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupchckBox = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblBrandName = new javax.swing.JLabel();
        lblManufactureDate = new javax.swing.JLabel();
        lblSeatCount = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        lblVehicleInsurance = new javax.swing.JLabel();
        lblRideOption = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtManufactureDate = new javax.swing.JTextField();
        chcSeatCount = new java.awt.Choice();
        txtSerialNumber = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtVehicleInsurance = new javax.swing.JTextField();
        comboRideOption = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        chckYes = new javax.swing.JCheckBox();
        chckNo = new javax.swing.JCheckBox();
        lblAvailable = new javax.swing.JLabel();
        radioCertified = new javax.swing.JRadioButton();
        radioNotCertified = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Car Details");

        lblBrandName.setForeground(new java.awt.Color(255, 255, 255));
        lblBrandName.setText("Brand Name:");

        lblManufactureDate.setForeground(new java.awt.Color(255, 255, 255));
        lblManufactureDate.setText("Manufactured Date:");

        lblSeatCount.setForeground(new java.awt.Color(255, 255, 255));
        lblSeatCount.setText("Seat Count:");

        lblSerialNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblSerialNumber.setText("Serial Number:");

        lblModelNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblModelNumber.setText("Model Number:");

        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City:");

        lblMaintenanceCertificate.setForeground(new java.awt.Color(255, 255, 255));
        lblMaintenanceCertificate.setText("Available:");

        lblVehicleInsurance.setForeground(new java.awt.Color(255, 255, 255));
        lblVehicleInsurance.setText("Vehicle Insurance:");

        lblRideOption.setForeground(new java.awt.Color(255, 255, 255));
        lblRideOption.setText("Ride option:");

        txtBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandNameActionPerformed(evt);
            }
        });

        txtManufactureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureDateActionPerformed(evt);
            }
        });

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        comboRideOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uber Rent", "Uber Green", "Uber X", "Uber Pool" }));
        comboRideOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRideOptionActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(0, 0, 0));
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        buttonGroupchckBox.add(chckYes);
        chckYes.setForeground(new java.awt.Color(255, 255, 255));
        chckYes.setText("Yes");

        buttonGroupchckBox.add(chckNo);
        chckNo.setForeground(new java.awt.Color(255, 255, 255));
        chckNo.setText("No");

        lblAvailable.setBackground(new java.awt.Color(0, 0, 0));
        lblAvailable.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailable.setText("Maintenance Certificate");

        radioCertified.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(radioCertified);
        radioCertified.setForeground(new java.awt.Color(255, 255, 255));
        radioCertified.setText("Certified");

        radioNotCertified.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(radioNotCertified);
        radioNotCertified.setForeground(new java.awt.Color(255, 255, 255));
        radioNotCertified.setText("Not Certified");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uber3.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManufactureDate)
                    .addComponent(lblBrandName)
                    .addComponent(lblSerialNumber)
                    .addComponent(lblModelNumber)
                    .addComponent(lblMaintenanceCertificate)
                    .addComponent(lblSeatCount)
                    .addComponent(lblCity)
                    .addComponent(lblVehicleInsurance)
                    .addComponent(lblRideOption)
                    .addComponent(lblAvailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVehicleInsurance)
                    .addComponent(comboRideOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCity)
                    .addComponent(txtModelNumber)
                    .addComponent(txtSerialNumber)
                    .addComponent(chcSeatCount, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufactureDate)
                    .addComponent(txtBrandName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chckYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chckNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioCertified)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioNotCertified)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(btnsave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrandName)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManufactureDate)
                    .addComponent(txtManufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSeatCount)
                    .addComponent(chcSeatCount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNumber)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chckYes)
                    .addComponent(chckNo)
                    .addComponent(lblMaintenanceCertificate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehicleInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRideOption)
                    .addComponent(comboRideOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailable)
                    .addComponent(radioCertified)
                    .addComponent(radioNotCertified))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        chcSeatCount.add("2");
        chcSeatCount.add("4");
        chcSeatCount.add("6");
        comboRideOption.addItem("Uber Taxi");
        comboRideOption.addItem("Uber Intercity");
        comboRideOption.addItem("Uber XL");
        comboRideOption.addItem("Uber Comfort");
        comboRideOption.addItem("Uber black");
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String maintenanceCertificate=null;
        String available = null;
        String carbrand=txtBrandName.getText();
        String manufacture=txtManufactureDate.getText();
        Integer seatCount =Integer.parseInt(chcSeatCount.getSelectedItem());
        Long serialNumber=Long.parseLong(txtSerialNumber.getText());
        String modelNumber= txtModelNumber.getText();
        String city= txtCity.getText();
        if(chckYes.isSelected()){
            maintenanceCertificate= chckYes.getText();
        }else if(chckNo.isSelected()){
           maintenanceCertificate= chckNo.getText();

        }
        if(radioCertified.isSelected()){
            available= radioCertified.getText();
        }else if(radioNotCertified.isSelected()){
           available= radioNotCertified.getText();

        }
        Long vehicleInsurance=Long.parseLong(txtVehicleInsurance.getText());
        String uberType=comboRideOption.getSelectedItem().toString();
        String fleetCreationDate = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
       
        UberDetails ud = catalog.addNewDetails();
        ud.setCarbrand(carbrand);
        ud.setManufacture(manufacture);
        ud.setSeatCount(seatCount);
        ud.setSerialNumber(serialNumber);
        ud.setModelNumber(modelNumber);
        ud.setCity(city);
        ud.setMaintenanceCertificate(maintenanceCertificate);
        ud.setAvailable(available);
        ud.setVehicleInsurance(vehicleInsurance);
        ud.setUberType(uberType);
        ud.setFleetCatalogEntryDate(fleetCreationDate);
//        ud.setIndexNumber();
//         int num = ud.getIndexNumber();
//        ud.setIndexNumber(num);
        JOptionPane.showMessageDialog(this, "Car details added.");
        txtBrandName.setText("");
        txtManufactureDate.setText("");
        txtSerialNumber.setText("");
        txtModelNumber.setText("");
        txtCity.setText("");
        txtVehicleInsurance.setText("");

    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandNameActionPerformed

    private void comboRideOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRideOptionActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_comboRideOptionActionPerformed

    private void txtManufactureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureDateActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupchckBox;
    private java.awt.Choice chcSeatCount;
    private javax.swing.JCheckBox chckNo;
    private javax.swing.JCheckBox chckYes;
    private javax.swing.JComboBox<String> comboRideOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblManufactureDate;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblRideOption;
    private javax.swing.JLabel lblSeatCount;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleInsurance;
    private javax.swing.JRadioButton radioCertified;
    private javax.swing.JRadioButton radioNotCertified;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufactureDate;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtVehicleInsurance;
    // End of variables declaration//GEN-END:variables



}
