/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Choice;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.UberCatalog;
import model.UberDetails;

/**
 *
 * @author tarushukla
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    UberCatalog catalog;
            
    public CreateJPanel(UberCatalog catalog) {
        initComponents();
        this.catalog= catalog;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblBrandName = new javax.swing.JLabel();
        lblManufactureDate = new javax.swing.JLabel();
        lblSeatCount = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        lblVehicleInsurance = new javax.swing.JLabel();
        lblRideOption = new javax.swing.JLabel();
        txtBrandName = new javax.swing.JTextField();
        txtManufactureDate = new javax.swing.JTextField();
        chcSeatCount = new java.awt.Choice();
        txtSerialNumber = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtVehicleInsurance = new javax.swing.JTextField();
        comboRideOption = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Car Details");

        lblBrandName.setText("Brand Name:");

        lblManufactureDate.setText("Manufactured Date:");

        lblSeatCount.setText("Seat Count:");

        lblSerialNumber.setText("Serial Number:");

        lblModelNumber.setText("Model Number:");

        lblCity.setText("City:");

        lblMaintenanceCertificate.setText("Maintenance Certificate:");

        lblVehicleInsurance.setText("Vehicle Insurance:");

        lblRideOption.setText("Ride option:");

        txtBrandName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandNameActionPerformed(evt);
            }
        });

        txtManufactureDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufactureDateActionPerformed(evt);
            }
        });

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        comboRideOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Uber Rent", "Uber Green", "Uber X", "Uber Pool" }));
        comboRideOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRideOptionActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButton1);
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButton2);
        jRadioButton2.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblManufactureDate)
                                    .addComponent(lblBrandName)
                                    .addComponent(lblSerialNumber)
                                    .addComponent(lblModelNumber)
                                    .addComponent(lblMaintenanceCertificate)
                                    .addComponent(lblSeatCount)
                                    .addComponent(lblCity)
                                    .addComponent(lblVehicleInsurance)
                                    .addComponent(lblRideOption))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtModelNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtManufactureDate, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBrandName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comboRideOption, javax.swing.GroupLayout.Alignment.LEADING, 0, 217, Short.MAX_VALUE)
                                        .addComponent(txtVehicleInsurance, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(chcSeatCount, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(btnsave)))
                        .addGap(0, 246, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrandName)
                    .addComponent(txtBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufactureDate)
                    .addComponent(txtManufactureDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeatCount)
                    .addComponent(chcSeatCount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNumber)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintenanceCertificate)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVehicleInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRideOption)
                    .addComponent(comboRideOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnsave)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        chcSeatCount.add("2");
        chcSeatCount.add("4");
        chcSeatCount.add("6");
        comboRideOption.addItem("Uber Taxi");
        comboRideOption.addItem("Uber Intercity");
        comboRideOption.addItem("Uber XL");
        comboRideOption.addItem("Uber Comfort");
        comboRideOption.addItem("Uber black");
        if(jRadioButton1.isSelected()){
            System.out.println("Yes");
        }
        if(jRadioButton2.isSelected()){
            System.out.println("No");
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String carbrand=txtBrandName.getText();
        String manufacture=txtManufactureDate.getText();
        Integer seatCount =Integer.parseInt(chcSeatCount.getSelectedItem().toString());
        Long serialNumber=Long.parseLong(txtSerialNumber.getText());
        String modelNumber= txtModelNumber.getText();
        String city= txtCity.getText();
//        
//        radioMaintenance1 = new JRadioButton("Yes");
//        radioMaintenance1.setActionCommand("Yes");
//        radioMaintenance2 = new JRadioButton("No");
//        radioMaintenance2.setActionCommand("No");
//        
//        group = new ButtonGroup();
//        group.add(radioMaintenance1);
//        group.add(radioMaintenance2);
//        
//        this.add(radioMaintenance1);
//        this.add(radioMaintenance2);
//        this.setVisible(true);
//
//        
        String maintenanceCertificate = buttonGroup.getSelection().getActionCommand();
//        System.out.println(group.getSelection().toString());
//        if(buttonGroup1.isSelected()){
//            maintenanceCertificate="Yes";
//        }else{
//                    maintenanceCertificate="No";
//    }
        Long vehicleInsurance=Long.parseLong(txtVehicleInsurance.getText());
        String uberType=comboRideOption.getSelectedItem().toString();
        
        UberDetails ud = catalog.addNewDetails();
        ud.setCarbrand(carbrand);
        ud.setManufacture(manufacture);
        ud.setSeatCount(seatCount);
        ud.setSerialNumber(serialNumber);
        ud.setModelNumber(modelNumber);
        ud.setCity(city);
        ud.setMaintenanceCertificate(maintenanceCertificate);
        ud.setVehicleInsurance(vehicleInsurance);
        ud.setUberType(uberType);
        
        JOptionPane.showMessageDialog(this, "Car details added.");
        txtBrandName.setText("");
        txtManufactureDate.setText("");
        txtSerialNumber.setText("");
        txtModelNumber.setText("");
        txtCity.setText("");
        txtVehicleInsurance.setText("");

    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtBrandNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandNameActionPerformed

    private void comboRideOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRideOptionActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_comboRideOptionActionPerformed

    private void txtManufactureDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufactureDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufactureDateActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.ButtonGroup buttonGroup;
    private java.awt.Choice chcSeatCount;
    private javax.swing.JComboBox<String> comboRideOption;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblBrandName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblManufactureDate;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblRideOption;
    private javax.swing.JLabel lblSeatCount;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleInsurance;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtManufactureDate;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    private javax.swing.JTextField txtVehicleInsurance;
    // End of variables declaration//GEN-END:variables

    private void maintainCertificate() {
//        radioMaintenance1 = new JRadioButton("Yes");
//        radioMaintenance1.setActionCommand("Yes");
//        radioMaintenance2 = new JRadioButton("No");
//        radioMaintenance2.setActionCommand("No");
        
//        group = new ButtonGroup();
//        group.add(radioMaintenance1);
//        group.add(radioMaintenance2);
    }


}
