/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Taru Shukla
 */
public class AdimGraphJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdimgraphJFrame
     */
    public AdimGraphJFrame() {
        initComponents();
        showUniversityPieChart();
        showProfBarChart();
        showStudentBarChart();
    }
    public void showProfBarChart(){

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        dataset.setValue(10, "Points", "CGPA");

        dataset.setValue(0, "Points", "Certification");

        dataset.setValue(2.5, "Points", "Projects");

        dataset.setValue(2.5, "Points", "Research");

        

        JFreeChart chart = ChartFactory.createBarChart("Student's Performance Indicator","Performace Attributes","Points",

                dataset, PlotOrientation.VERTICAL, false,true,false);

        CategoryPlot categoryPlot =  chart.getCategoryPlot();

        categoryPlot.setBackgroundPaint(Color.WHITE);

       BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();

        Color clr3 = new Color(255,255,102);

        renderer.setSeriesPaint(0, clr3);
        ChartPanel barpChartPanel = new ChartPanel(chart);

        profbarChart.removeAll();

        profbarChart.add(barpChartPanel, BorderLayout.CENTER);

        profbarChart.validate();

    }
    public void showUniversityPieChart(){

      DefaultPieDataset barDataset = new DefaultPieDataset( );

      barDataset.setValue( "Student's Performance" , 10  );

      barDataset.setValue( "Professor's Performance" , 7.5);   

      barDataset.setValue( "Student's Employment Performance " , 7.5);    

      barDataset.setValue( "Extra Curricular" , 2.5 );

       JFreeChart piechart = ChartFactory.createPieChart("University Performance Indicator",barDataset, false,true,false);//explain

        PiePlot piePlot =(PiePlot) piechart.getPlot();


       piePlot.setSectionPaint("Student's Performance", new Color(255,255,102));

        piePlot.setSectionPaint("Professor's Performance", new Color(102,255,102));

        piePlot.setSectionPaint("Student's Employment Performance ", new Color(255,102,153));

        piePlot.setSectionPaint("Extra Curricular", new Color(0,204,204));

        piePlot.setBackgroundPaint(Color.white);

        //create chartPanel to display chart(graph)

        ChartPanel barChartPanel = new ChartPanel(piechart);

        uniPieChartPanel.removeAll();

        uniPieChartPanel.add(barChartPanel, BorderLayout.CENTER);

        uniPieChartPanel.validate();

    }
    public void showStudentBarChart(){

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        dataset.setValue(5, "Points", "Research Paper");

        dataset.setValue(5, "Points", "Certification");

        dataset.setValue(7.5, "Points", "Projects");
         dataset.setValue(7.5, "Points", "Student Rating");
        dataset.setValue(10, "Points","Industry Experience");

       
        JFreeChart chart = ChartFactory.createBarChart("Professor's Performace Indicator","Performace Attributes","Points",

                dataset, PlotOrientation.VERTICAL, false,true,false);


        CategoryPlot categoryPlot =  chart.getCategoryPlot();


        categoryPlot.setBackgroundPaint(Color.WHITE);

       BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();

        Color clr3 = new Color(204,0,51);

        renderer.setSeriesPaint(0, clr3);

        ChartPanel barpChartPanel = new ChartPanel(chart);

        studentbarChart.removeAll();

        studentbarChart.add(barpChartPanel, BorderLayout.CENTER);

        studentbarChart.validate();

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        studentbarChart = new javax.swing.JPanel();
        profbarChart = new javax.swing.JPanel();
        uniPieChartPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentbarChart.setBackground(new java.awt.Color(255, 153, 51));
        studentbarChart.setLayout(new java.awt.BorderLayout());
        getContentPane().add(studentbarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 760, 330));

        profbarChart.setBackground(new java.awt.Color(204, 255, 204));
        profbarChart.setLayout(new java.awt.BorderLayout());
        getContentPane().add(profbarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, 430, 260));

        uniPieChartPanel.setBackground(new java.awt.Color(204, 255, 204));
        uniPieChartPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(uniPieChartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 360, 260));

        jPanel1.setBackground(new java.awt.Color(228, 193, 207));

        jLabel1.setText("Select Student:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "001234568", "001234569", "001234565", "001234564", "001234563", "001234544" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 60));

        jPanel2.setBackground(new java.awt.Color(228, 193, 207));

        jLabel2.setBackground(new java.awt.Color(228, 193, 207));
        jLabel2.setText("Select Faculty:");

        jComboBox2.setBackground(new java.awt.Color(228, 193, 207));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Khaled M. Bugrara", "Amuthan Arulraj", "Laura A. Meyer" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 60));

        jPanel3.setBackground(new java.awt.Color(228, 193, 207));

        jLabel3.setText("View Performance for the Year:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("2021");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2017");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("2020");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("2019");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("2018");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdimGraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdimGraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdimGraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdimGraphJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdimGraphJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JPanel profbarChart;
    private javax.swing.JPanel studentbarChart;
    private javax.swing.JPanel uniPieChartPanel;
    // End of variables declaration//GEN-END:variables
}
