/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author NetrA
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnGuest = new javax.swing.JButton();
        btnFaculty = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setPreferredSize(new java.awt.Dimension(1035, 300));

        controlPanel.setBackground(new java.awt.Color(0, 0, 0));
        controlPanel.setPreferredSize(new java.awt.Dimension(200, 600));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdmin.setText("Admin login");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        controlPanel.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, -1));

        btnGuest.setText("Guest login");
        btnGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestActionPerformed(evt);
            }
        });
        controlPanel.add(btnGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 153, -1));

        btnFaculty.setText("Faculty login");
        btnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyActionPerformed(evt);
            }
        });
        controlPanel.add(btnFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 153, -1));

        btnStudent.setText("Student login");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        controlPanel.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 153, -1));

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(232, 64, 64));
        workArea.setPreferredSize(new java.awt.Dimension(622, 600));
        workArea.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(246, 176, 176));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/neu.gif"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 160));
        workArea.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 980, 660));

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
       // CreateJPanel createpanel = new CreateJPanel(history);
        AdminLoginJPanleJPanel graphpanel = new AdminLoginJPanleJPanel();
        splitPane.setRightComponent(graphpanel);
        
        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestActionPerformed
        GuestLoginJPanel guestpanel = new GuestLoginJPanel();
        splitPane.setRightComponent(guestpanel);
    }//GEN-LAST:event_btnGuestActionPerformed

    private void btnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyActionPerformed
        // TODO add your handling code here:
        FacultyLoginJPanel facultypanel = new FacultyLoginJPanel();
        splitPane.setRightComponent(facultypanel);
        
    }//GEN-LAST:event_btnFacultyActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
         StudentLoginPanel sgraphpanel = new StudentLoginPanel();
       splitPane.setRightComponent(sgraphpanel);
    }//GEN-LAST:event_btnStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnFaculty;
    private javax.swing.JButton btnGuest;
    private javax.swing.JButton btnStudent;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
